module.exports = 
[
  {
    Unit_ID: 1001,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '4.0',
    Unit_Name: 'M28 Squad',
    Firepower: 19300,
    HP: 10300,
    Speed: 25,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1002,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '4.1',
    Unit_Name: 'Karabiner 98k Squad',
    Firepower: 24200,
    HP: 13000,
    Speed: 25,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1003,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '5.0',
    Unit_Name: 'Gewehr 41 Squad',
    Firepower: 31300,
    HP: 16300,
    Speed: 28,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1004,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '5.1',
    Unit_Name: 'Gewehr 43 Squad',
    Firepower: 38700,
    HP: 20600,
    Speed: 28,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1005,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '6.0',
    Unit_Name: 'Suomi KP/-31 Squad',
    Firepower: 48600,
    HP: 25900,
    Speed: 30,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1006,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '6.1',
    Unit_Name: 'MP40 Squad',
    Firepower: 61800,
    HP: 32700,
    Speed: 30,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1007,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '7.0',
    Unit_Name: 'StG 44 Squad',
    Firepower: 77500,
    HP: 41200,
    Speed: 33,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1008,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '7.1',
    Unit_Name: 'RK 62 Squad',
    Firepower: 97200,
    HP: 51900,
    Speed: 33,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1009,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '7.2',
    Unit_Name: 'M76 Squad',
    Firepower: 123000,
    HP: 65400,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1010,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '8.0',
    Unit_Name: 'G3 Squad',
    Firepower: 138000,
    HP: 73500,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1011,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '8.1',
    Unit_Name: 'G36 Squad',
    Firepower: 154000,
    HP: 82500,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1012,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '8.2',
    Unit_Name: 'G36K Squad',
    Firepower: 174000,
    HP: 92600,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1013,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '9.0',
    Unit_Name: 'MP5 Squad',
    Firepower: 195000,
    HP: 103000,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1014,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '9.1',
    Unit_Name: 'UMP45 Squad',
    Firepower: 219000,
    HP: 116000,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1015,
    Camp: 'Vanguard',
    Unit_Type: 'Infantry',
    Unit_Level: '9.2',
    Unit_Name: 'MP7 Squad',
    Firepower: 246000,
    HP: 130000,
    Speed: 35,
    Attack_Type: 'Ground',
    Image: 'VanguardInfantry.jpg'
  },
  {
    Unit_ID: 1016,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '4.0',
    Unit_Name: 'Panzer III Ausf. E',
    Firepower: 72300,
    HP: 35800,
    Speed: 38,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1017,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '4.1',
    Unit_Name: 'Panzer III Ausf. G',
    Firepower: 90600,
    HP: 45200,
    Speed: 38,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1018,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '5.0',
    Unit_Name: 'Panzer IV Ausf. A',
    Firepower: 114000,
    HP: 56900,
    Speed: 39,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1019,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '5.1',
    Unit_Name: 'Panzer IV Ausf. D',
    Firepower: 144000,
    HP: 71700,
    Speed: 39,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1020,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '6.0',
    Unit_Name: 'Panzer IV Ausf. G',
    Firepower: 182000,
    HP: 90400,
    Speed: 40,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1021,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '6.1',
    Unit_Name: 'Panzer IV Ausf. H',
    Firepower: 229000,
    HP: 113000,
    Speed: 40,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1022,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '7.0',
    Unit_Name: 'Panzer Ausf. D',
    Firepower: 289000,
    HP: 143000,
    Speed: 43,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1023,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '7.1',
    Unit_Name: 'Panzer Ausf. A',
    Firepower: 365000,
    HP: 180000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1024,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '7.2',
    Unit_Name: 'Panzer Ausf. G',
    Firepower: 459000,
    HP: 227000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1025,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '8.0',
    Unit_Name: 'AMX-13',
    Firepower: 667000,
    HP: 401000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1026,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '8.1',
    Unit_Name: 'AMX-30',
    Firepower: 749000,
    HP: 451000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1027,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '8.2',
    Unit_Name: 'AMX-30B2',
    Firepower: 841000,
    HP: 506000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1028,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '9.0',
    Unit_Name: 'Leopard 1A1',
    Firepower: 944000,
    HP: 568000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1029,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '9.1',
    Unit_Name: 'Leopard 1A4',
    Firepower: 1050000,
    HP: 638000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1030,
    Camp: 'Vanguard',
    Unit_Type: 'MediumTanks',
    Unit_Level: '9.2',
    Unit_Name: 'Leopard 2',
    Firepower: 1190000,
    HP: 716000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardMediumTanks.jpg'
  },
  {
    Unit_ID: 1031,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '4.0',
    Unit_Name: 'VK 30.01 (H)',
    Firepower: 88900,
    HP: 56300,
    Speed: 29,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1032,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '4.1',
    Unit_Name: 'VK 36.01 (H)',
    Firepower: 112000,
    HP: 71000,
    Speed: 29,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1033,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '5.0',
    Unit_Name: 'Tiger (P)',
    Firepower: 141000,
    HP: 89500,
    Speed: 30,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1034,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '5.1',
    Unit_Name: 'Tiger (P) Commandant',
    Firepower: 178000,
    HP: 112000,
    Speed: 30,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1035,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '6.0',
    Unit_Name: 'Tiger I',
    Firepower: 225000,
    HP: 142000,
    Speed: 31,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1036,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '6.1',
    Unit_Name: 'Tiger I Ausf. E',
    Firepower: 283000,
    HP: 179000,
    Speed: 31,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1037,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '7.0',
    Unit_Name: 'Tiger II',
    Firepower: 357000,
    HP: 225000,
    Speed: 33,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1038,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '7.1',
    Unit_Name: 'Tiger II (H)',
    Firepower: 449000,
    HP: 284000,
    Speed: 33,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1039,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '7.2',
    Unit_Name: 'Tiger II Ausf. B',
    Firepower: 566000,
    HP: 358000,
    Speed: 33,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1040,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '8.0',
    Unit_Name: 'AMX-13',
    Firepower: 667000,
    HP: 401000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1041,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '8.1',
    Unit_Name: 'AMX-30',
    Firepower: 749000,
    HP: 451000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1042,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '8.2',
    Unit_Name: 'AMX-30B2',
    Firepower: 841000,
    HP: 506000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1043,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '9.0',
    Unit_Name: 'Leopard 1A1',
    Firepower: 944000,
    HP: 568000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1044,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '9.1',
    Unit_Name: 'Leopard 1A4',
    Firepower: 1050000,
    HP: 638000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1045,
    Camp: 'Vanguard',
    Unit_Type: 'HeavyTanks',
    Unit_Level: '9.2',
    Unit_Name: 'Leopard 2',
    Firepower: 1190000,
    HP: 716000,
    Speed: 45,
    Attack_Type: 'Ground',
    Image: 'VanguardHeavyTanks.jpg'
  },
  {
    Unit_ID: 1046,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '4.0',
    Unit_Name: 'Marder I',
    Firepower: 74000,
    HP: 30700,
    Speed: 38,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1047,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '4.1',
    Unit_Name: 'Marder II',
    Firepower: 92900,
    HP: 38700,
    Speed: 38,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1048,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '5.0',
    Unit_Name: 'Hetzer',
    Firepower: 117000,
    HP: 48800,
    Speed: 40,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1049,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '5.1',
    Unit_Name: 'StuG III',
    Firepower: 148000,
    HP: 61500,
    Speed: 41,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1050,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '6.0',
    Unit_Name: 'Nashorn',
    Firepower: 186000,
    HP: 77500,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1051,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '6.1',
    Unit_Name: 'Hummel',
    Firepower: 234000,
    HP: 97600,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1052,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '7.0',
    Unit_Name: 'Jagdpanther',
    Firepower: 296000,
    HP: 123000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1053,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '7.1',
    Unit_Name: 'Elefant',
    Firepower: 373000,
    HP: 155000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1054,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '7.2',
    Unit_Name: 'Jagdtiger',
    Firepower: 470000,
    HP: 195000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1055,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '8.0',
    Unit_Name: 'SA 342M Gazelle',
    Firepower: 791000,
    HP: 328000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1056,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '8.1',
    Unit_Name: 'SA 319B Alouette III',
    Firepower: 888000,
    HP: 369000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1057,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '8.2',
    Unit_Name: 'AS565 Panther',
    Firepower: 997000,
    HP: 414000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1058,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '9.0',
    Unit_Name: 'A129 Mangusta',
    Firepower: 1110000,
    HP: 465000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1059,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '9.1',
    Unit_Name: 'T129 ATAK',
    Firepower: 1250000,
    HP: 522000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1060,
    Camp: 'Vanguard',
    Unit_Type: 'TankHunters',
    Unit_Level: '9.2',
    Unit_Name: 'EC665 Tiger',
    Firepower: 1400000,
    HP: 585000,
    Speed: 44,
    Attack_Type: 'Ground',
    Image: 'VanguardTankHunters.jpg'
  },
  {
    Unit_ID: 1061,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '5.0',
    Unit_Name: 'Lowe',
    Firepower: 163000,
    HP: 130000,
    Speed: 19,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1062,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '5.1',
    Unit_Name: 'Schwerer Lowe',
    Firepower: 204000,
    HP: 164000,
    Speed: 19,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1063,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '6.0',
    Unit_Name: 'E-50',
    Firepower: 258000,
    HP: 206000,
    Speed: 20,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1064,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '6.1',
    Unit_Name: 'E-75',
    Firepower: 325000,
    HP: 260000,
    Speed: 20,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1065,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '7.0',
    Unit_Name: 'Maus Prototype',
    Firepower: 410000,
    HP: 328000,
    Speed: 21,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1066,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '7.1',
    Unit_Name: 'Maus V1',
    Firepower: 516000,
    HP: 413000,
    Speed: 21,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1067,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '7.2',
    Unit_Name: 'Maus V2',
    Firepower: 650000,
    HP: 520000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1068,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '8.0',
    Unit_Name: 'E-100',
    Firepower: 1090000,
    HP: 876000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1069,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '8.1',
    Unit_Name: 'E-100 (Maus Turret)',
    Firepower: 1230000,
    HP: 984000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1070,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '8.2',
    Unit_Name: 'E-100 (Krupp Turret)',
    Firepower: 1380000,
    HP: 1100000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1071,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '9.0',
    Unit_Name: 'Karl-Gerat',
    Firepower: 1550000,
    HP: 1240000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1072,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '9.1',
    Unit_Name: 'P.1000 Ratte',
    Firepower: 1740000,
    HP: 1390000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1073,
    Camp: 'Vanguard',
    Unit_Type: 'SuperHeavyTanks',
    Unit_Level: '9.2',
    Unit_Name: 'P.1500 Monster',
    Firepower: 1950000,
    HP: 1560000,
    Speed: 23,
    Attack_Type: 'Ground',
    Image: 'VanguardSuperHeavy.jpg'
  },
  {
    Unit_ID: 1074,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '4.0',
    Unit_Name: '10.5cm IeFH 16',
    Firepower: 64200,
    HP: 12700,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1075,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '4.1',
    Unit_Name: '10.5cm IeFH 18',
    Firepower: 80900,
    HP: 16100,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1076,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '5.0',
    Unit_Name: '7.5cm Pak 40',
    Firepower: 101000,
    HP: 20200,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1077,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '5.1',
    Unit_Name: '7.5cm Pak 41',
    Firepower: 128000,
    HP: 25500,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1078,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '6.0',
    Unit_Name: '8.8cm Flak 18',
    Firepower: 161000,
    HP: 32200,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1079,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '6.1',
    Unit_Name: '8.8cm Pak 43',
    Firepower: 203000,
    HP: 40600,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1080,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '7.0',
    Unit_Name: '12.8cm Flak 40',
    Firepower: 256000,
    HP: 51100,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1081,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '7.1',
    Unit_Name: '12.8cm Pak 44',
    Firepower: 323000,
    HP: 64400,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1082,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '7.2',
    Unit_Name: '12.8cm Flak 40/2',
    Firepower: 407000,
    HP: 81200,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1083,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '8.0',
    Unit_Name: '105mm MIe 1950',
    Firepower: 457000,
    HP: 91100,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1084,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '8.1',
    Unit_Name: 'Mk 61 105mm',
    Firepower: 513000,
    HP: 102000,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1085,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '8.2',
    Unit_Name: '155mm MIe 50',
    Firepower: 576000,
    HP: 114000,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1086,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '9.0',
    Unit_Name: 'Mk F3 155mm',
    Firepower: 646000,
    HP: 128000,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1087,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '9.1',
    Unit_Name: 'CAESAR',
    Firepower: 726000,
    HP: 144000,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1088,
    Camp: 'Vanguard',
    Unit_Type: 'AntiTankGuns',
    Unit_Level: '9.2',
    Unit_Name: 'PzH 2000',
    Firepower: 814000,
    HP: 162000,
    Speed: 15,
    Attack_Type: 'Ground',
    Image: 'VanguardAntiTankGuns.jpg'
  },
  {
    Unit_ID: 1089,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '5.0',
    Unit_Name: 'He 100',
    Firepower: 137000,
    HP: 48900,
    Speed: 150,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1090,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '5.1',
    Unit_Name: 'He 112',
    Firepower: 172000,
    HP: 61700,
    Speed: 155,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1091,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '6.0',
    Unit_Name: 'Bf 109',
    Firepower: 217000,
    HP: 77700,
    Speed: 159,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1092,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '6.1',
    Unit_Name: 'Me 209',
    Firepower: 276000,
    HP: 97900,
    Speed: 165,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1093,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '7.0',
    Unit_Name: 'Fw 190',
    Firepower: 348000,
    HP: 123000,
    Speed: 170,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1094,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '7.1',
    Unit_Name: 'Ta 152',
    Firepower: 440000,
    HP: 155000,
    Speed: 174,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1095,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '7.2',
    Unit_Name: 'Ta 183',
    Firepower: 559000,
    HP: 195000,
    Speed: 180,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1096,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '8.0',
    Unit_Name: 'Mirage III',
    Firepower: 623000,
    HP: 219000,
    Speed: 185,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1097,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '8.1',
    Unit_Name: 'Mirage 5',
    Firepower: 716000,
    HP: 246000,
    Speed: 191,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1098,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '8.2',
    Unit_Name: 'Mirage 50',
    Firepower: 813000,
    HP: 277000,
    Speed: 197,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1099,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '9.0',
    Unit_Name: 'Mirage 2000',
    Firepower: 918000,
    HP: 311000,
    Speed: 203,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
  {
    Unit_ID: 1100,
    Camp: 'Vanguard',
    Unit_Type: 'Fighters',
    Unit_Level: '9.1',
    Unit_Name: 'Tornado',
    Firepower: 1040000,
    HP: 349000,
    Speed: 209,
    Attack_Type: 'Air',
    Image: 'VanguardFighters.jpg'
  },
]